# This template is heavily inspired by anthropic's computer use demo
agent:
  templates:
    system_template: |-
      You are a helpful assistant that can interact with a computer to solve tasks.
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      你能帮助我实现必要的更改到仓库中，以满足 <pr_description> 中指定的要求吗？
      我已经完成了 <pr_description> 中描述的所有测试文件的更改。这意味着你不需要修改测试逻辑或任何测试文件！
      你的任务是对 {{working_dir}} 目录中的非测试文件进行最小化的更改，以确保满足 <pr_description> 的要求。
      按照以下步骤解决问题：
      1. 找到并阅读与 <pr_description> 相关的代码可能是个好主意。
      2. 创建一个脚本来重现错误，并使用 `python <filename.py>` 命令在 bash 工具中执行，以确认错误。
      3. 编辑仓库的源代码以解决问题。
      4. 重新运行你的重现脚本，并确认错误已修复。
    next_step_template: |-
      OBSERVATION:
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
  tools:
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
    registry_variables:
      USE_FILEMAP: 'true'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. If you have modified any TEST files, please revert them to the state they had before you started fixing the issue.
            You can do this with `git checkout -- /path/to/test/file.py`. Use below <diff> to find the files you need to revert.
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
    enable_bash_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: cache_control
      last_n_messages: 2
